### ISSUE TITLE
Svelte 4 compatibility

### ISSUE THREAD

**Issue by PixievoltNo1** [HellButcher/parcel-transformer-svelte3-plus#6]
[Svelte 4 is here!](https://svelte.dev/blog/svelte-4) I'm happy to report that this plugin mostly works with it as is, but there are some minor issues you could address for a smoother experience.

## Documentation

Svelte 4 was restructured to be importable exclusively by [package exports](https://parceljs.org/features/dependency-resolution/#package-exports), which Parcel doesn't support by default. I recommend you add a note to the readme including that link and asking users to turn that on so they won't run into errors.

## Console warning for `format` option

Svelte 4 doesn't support the `format` option any more, and prints a console warning when plugins like this one use it. It looks like official plugins get around this by importing `VERSION` from svelte/compiler and setting the option only when `VERSION[0] === '3'`.

**Comment by HellButcher** [comment]
Thanks for the analysis. I have made the changes, and will release them soon

**Comment by PixievoltNo1** [comment]
Thank you muchly for your efforts on v0.2.10!
